export const styles = {
  InputDescription: {
    fontSize: '16px',
    lineHeight: '24px',
    width: '87%',
    height: '48px',
    position: 'relative',
    cursor: 'auto',
    marginLeft: '50px',
  },
  Input: {
    cursor: 'pointer',
    width: 'auto',
    overflow: 'visible',
    display: 'block',
    height: '40px',
    lineHeight: '0',
    padding: '2%',
    borderRadius: '4px',
    border: 'solid 1px #cac5c5',
    transition: 'all .25s',
    fontSize: '15px',
    marginLeft: '50px',
    marginRight: '50px',
  },
  InputLeftSide: {
    cursor: 'pointer',
    width: '35%',
    overflow: 'visible',
    display: 'block',
    height: '40px',
    lineHeight: '0',
    padding: '2%',
    borderRadius: '4px',
    border: 'solid 1px #cac5c5',
    transition: 'all .25s',
    fontSize: '15px',
    marginLeft: '50px',
    float: 'left',
  },
  InputRightSide: {
    cursor: 'pointer',
    width: '43%',
    overflow: 'visible',
    display: 'block',
    height: '40px',
    lineHeight: '0',
    padding: '2%',
    borderRadius: '4px',
    border: 'solid 1px #cac5c5',
    transition: 'all .25s',
    fontSize: '15px',
    float: 'right',
    marginRight: '50px',
  },
  grayStyle: {
    fill: '#555555',
    fontSize: '15px',
    fontWeight: '500',
    fontStyle: 'normal',
    fontStretch: 'normal',
    lineHeight: 'normal',
    letterSpacing: 'normal',
    textAlign: 'left',
    color: '#555555',
    width: 'auto',
    display: 'contents',
  },
  groupRadioButton: {
    width: 'auto',
    margin: '10px 0 15px 50px',
  },
  radioButton: {
    marginRight: '40px',
    width: 'fit-content',
    display: 'inline-block',
    fill: '#555555',
  },
  textField: {
    marginTop: '0',
  },
  dropDownMenuStyle: {
    width: 'auto',
    textAlign: 'left',
    border: '1px solid rgb(202, 197, 197)',
    borderRadius: '4px',
    height: 40,
    margin: '0 50px 5px 50px',
    display: 'block',
  },
  dropDownMenuUnderline: {
    display: 'none',
  },
  dropDownMenuLabel: {
    fontFamily: 'Avenir',
    fontSize: '16px',
    fontWeight: '500',
    color: '#555555',
    paddingLeft: 16,
    height: 40,
    lineHeight: '40px',
  },
  dropDownMenuIcon: {
    fill: 'rgb(202, 197, 197)',
    right: 0,
    top: 0,
    padding: 8,
    width: 40,
    height: 40,
  },
  selected: {
    color: 'rgb(69, 107, 174)',
  },
  TableHeaderStyledTabOne: {
    width: '30%',
    height: '22px',
    fontSize: '16px',
    fontWeight: 'normal',
    fontStyle: 'normal',
    fontStretch: 'normal',
    paddingLeft: '0',
    paddingRight: '0',
    lineHeight: 'normal',
    letterSpacing: 'normal',
    textAlign: 'center',
    color: '#8c8c8c',
  },
  TableHeaderStyledTabTwo: {
    width: '68%',
    height: '22px',
    fontSize: '16px',
    fontWeight: 'normal',
    fontStyle: 'normal',
    fontStretch: 'normal',
    paddingLeft: '0',
    paddingRight: '0',
    lineHeight: 'normal',
    letterSpacing: 'normal',
    textAlign: 'center',
    color: '#8c8c8c',
  },
  TableHeaderStyledTabFive: {
    width: '58%',
    height: '22px',
    fontSize: '16px',
    fontWeight: 'normal',
    fontStyle: 'normal',
    fontStretch: 'normal',
    paddingLeft: '0',
    paddingRight: '0',
    lineHeight: 'normal',
    letterSpacing: 'normal',
    textAlign: 'center',
    color: '#8c8c8c',
  },
  TableHeaderStyled: {
    width: '48%',
    height: '22px',
    fontSize: '16px',
    fontWeight: 'normal',
    fontStyle: 'normal',
    fontStretch: 'normal',
    paddingLeft: '0',
    paddingRight: '0',
    lineHeight: 'normal',
    letterSpacing: 'normal',
    textAlign: 'center',
    color: '#8c8c8c',
  },
  TableHeaderHeight: {
    height: '70px',
  },
  TableHeaderStyledImages: {
    width: '5%',
    height: '22px',
    fontSize: '16px',
    fontWeight: 'normal',
    fontStyle: 'normal',
    fontStretch: 'normal',
    paddingLeft: '37px',
    lineHeight: 'normal',
    letterSpacing: 'normal',
    textAlign: 'left',
    color: '#8c8c8c',
  },
  TableHeaderStyledButtons: {
    width: '10%',
    height: '22px',
    fontSize: '16px',
    fontWeight: 'normal',
    fontStyle: 'normal',
    fontStretch: 'normal',
    paddingLeft: '37px',
    lineHeight: 'normal',
    letterSpacing: 'normal',
    textAlign: 'left',
    color: '#8c8c8c',
  },
};
